name: Releases

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pierre781/sls-local-server

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true

      - run: go build -o main main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sls-local-server
          path: main
      